from datetime import datetime

from sqlalchemy import DateTime, func
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base
from app.db.mixins import TimestampMixin, UUIDPrimaryKeyMixin


class Client(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """A browser identified by the anonymous UUID it sends in X-Client-Id (v1 has no login).

    The id is the header value itself (generated by the frontend), not by Postgres. It
    identifies but doesn't authenticate, so no personal data is stored here.
    """

    __tablename__ = "clients"

    # Separate from updated_at so later columns (e.g. linking to a User in Epic D) don't
    # get mixed up with "this browser was seen".
    last_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
