"""create presets table

Revision ID: dd4049e2d825
Revises: 276a2b91c20b
Create Date: 2026-10-08 13:19:12.542199

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd4049e2d825"
down_revision: Union[str, None] = "276a2b91c20b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "presets",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("pages", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rain", sa.Integer(), server_default="0", nullable=False),
        sa.Column("clock", sa.Integer(), server_default="0", nullable=False),
        sa.Column("whispers", sa.Integer(), server_default="0", nullable=False),
        sa.Column("fire", sa.Integer(), server_default="0", nullable=False),
        sa.Column("keys", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("clock >= 0 AND clock <= 100", name=op.f("ck_presets_clock_range")),
        sa.CheckConstraint("fire >= 0 AND fire <= 100", name=op.f("ck_presets_fire_range")),
        sa.CheckConstraint("keys >= 0 AND keys <= 100", name=op.f("ck_presets_keys_range")),
        sa.CheckConstraint("pages >= 0 AND pages <= 100", name=op.f("ck_presets_pages_range")),
        sa.CheckConstraint("rain >= 0 AND rain <= 100", name=op.f("ck_presets_rain_range")),
        sa.CheckConstraint(
            "whispers >= 0 AND whispers <= 100", name=op.f("ck_presets_whispers_range")
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_presets_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_presets")),
    )
    op.create_index("ix_presets_client_id", "presets", ["client_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_presets_client_id", table_name="presets")
    op.drop_table("presets")
    # ### end Alembic commands ###
